### ISSUE TITLE
installation requires ppxlib 0.25.0

### ISSUE THREAD

**Issue by nilsbecker** [thierry-martinez/ocaml-in-python#1]
the current version is 0.26.0 . is this intentional?

**Comment by thierry-martinez** [comment]
Thank you for reporting! No, that was not intentional: the packages `metapp`, `metaquot` and `ocaml-in-python` require new releases to be compatible with the last `ppxlib 0.26.0`. I just fixed them upstream: if you need these packages working with the last version of ppxlib before the upcoming release, you can pin them
```
opam pin https://github.com/thierry.martinez/metapp.git
opam pin https://github.com/thierry.martinez/metaquot.git
opam pin https://github.com/thierry.martinez/ocaml-in-python.git
```
